spring:
   data:
     mongodb:
        host: localhost
        port: 27017
        database: target

logging:
  level:
     org.springframework.data: debug
  pattern:
     console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

redskytarget: 
         url: https://redsky.target.com/v2/pdp/tcin/
         excludes: excludes=taxonomy,price,promotion,bulk_ship,rating_and_review_reviews,rating_and_review_statistics,question_answer_statistics
